//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintPDV.LanguagePack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintPDV.LanguagePack.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file not found..
        /// </summary>
        public static string Application_ErrorMessage_DatabaseNotFound {
            get {
                return ResourceManager.GetString("Application_ErrorMessage_DatabaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating folder &quot;{0}&quot;..
        /// </summary>
        public static string Application_ErrorMessage_FolderNotCreated {
            get {
                return ResourceManager.GetString("Application_ErrorMessage_FolderNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Activation&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_AppLicense_Required_Activation {
            get {
                return ResourceManager.GetString("ErrorMessage_AppLicense_Required_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Active&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_AppLicense_Required_Active {
            get {
                return ResourceManager.GetString("ErrorMessage_AppLicense_Required_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Identifier&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_AppLicense_Required_Identifier {
            get {
                return ResourceManager.GetString("ErrorMessage_AppLicense_Required_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Key&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_AppLicense_Required_Key {
            get {
                return ResourceManager.GetString("ErrorMessage_AppLicense_Required_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;PrintLimit&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_AppLicense_Required_PrintLimit {
            get {
                return ResourceManager.GetString("ErrorMessage_AppLicense_Required_PrintLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Identifier&quot; must be less or equal to 50 characters lenght..
        /// </summary>
        public static string ErrorMessage_AppLicense_StringLength_Identifier {
            get {
                return ResourceManager.GetString("ErrorMessage_AppLicense_StringLength_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Key&quot; must be 6 characters lenght..
        /// </summary>
        public static string ErrorMessage_AppLicense_StringLength_Key {
            get {
                return ResourceManager.GetString("ErrorMessage_AppLicense_StringLength_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;BorderWidth&quot; must be less or equal to 100..
        /// </summary>
        public static string ErrorMessage_Campaign_Range_BorderWidth {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Range_BorderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Active&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Campaign_Required_Active {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Required_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Created&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Campaign_Required_Created {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Required_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;CutType&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Campaign_Required_CutType {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Required_CutType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Name&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Campaign_Required_Name {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Required_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;PaperSize&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Campaign_Required_PaperSize {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Required_PaperSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;PrintDateTime&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Campaign_Required_PrintDateTime {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Required_PrintDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;PrintVoucher&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Campaign_Required_PrintVoucher {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Required_PrintVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;VoucherBarcodeType&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Campaign_Required_VoucherBarcodeType {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Required_VoucherBarcodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign field &quot;Name&quot; must be unique..
        /// </summary>
        public static string ErrorMessage_Campaign_Rule_UniqueName {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_Rule_UniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;BorderStyle&quot; must be less or equal to 20 characters lenght..
        /// </summary>
        public static string ErrorMessage_Campaign_StringLength_BorderStyle {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_StringLength_BorderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Name&quot; must be less or equal to 50 characters lenght..
        /// </summary>
        public static string ErrorMessage_Campaign_StringLength_Name {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_StringLength_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Shortcut&quot; must be less or equal to 10 characters lenght..
        /// </summary>
        public static string ErrorMessage_Campaign_StringLength_Shortcut {
            get {
                return ResourceManager.GetString("ErrorMessage_Campaign_StringLength_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;GalleryType&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_GalleryClipart_Required_GalleryType {
            get {
                return ResourceManager.GetString("ErrorMessage_GalleryClipart_Required_GalleryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Image&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_GalleryClipart_Required_Image {
            get {
                return ResourceManager.GetString("ErrorMessage_GalleryClipart_Required_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Name&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_GalleryClipart_Required_Name {
            get {
                return ResourceManager.GetString("ErrorMessage_GalleryClipart_Required_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clipart must be selected..
        /// </summary>
        public static string ErrorMessage_GalleryClipart_Required_NotSelected {
            get {
                return ResourceManager.GetString("ErrorMessage_GalleryClipart_Required_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Name&quot; must be less or equal to 50 characters lenght..
        /// </summary>
        public static string ErrorMessage_GalleryClipart_StringLength_Name {
            get {
                return ResourceManager.GetString("ErrorMessage_GalleryClipart_StringLength_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template must be selected..
        /// </summary>
        public static string ErrorMessage_GalleryTemplate_Required_NotSelected {
            get {
                return ResourceManager.GetString("ErrorMessage_GalleryTemplate_Required_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License expired..
        /// </summary>
        public static string ErrorMessage_License_Rule_Expired {
            get {
                return ResourceManager.GetString("ErrorMessage_License_Rule_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License not found..
        /// </summary>
        public static string ErrorMessage_License_Rule_NotFound {
            get {
                return ResourceManager.GetString("ErrorMessage_License_Rule_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License not valid..
        /// </summary>
        public static string ErrorMessage_License_Rule_NotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_License_Rule_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;ConnectionType&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Printer_Required_ConnectionType {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_Required_ConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Manufacturer&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Printer_Required_Manufacturer {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_Required_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Model&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Printer_Required_Model {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_Required_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Name&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Printer_Required_Name {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_Required_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Printer&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Printer_Required_PrinterNotSelected {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_Required_PrinterNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer handler was not resolved..
        /// </summary>
        public static string ErrorMessage_Printer_Rule_PrinterHandlerNotResolved {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_Rule_PrinterHandlerNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A printer must be defined..
        /// </summary>
        public static string ErrorMessage_Printer_Rule_PrinterNotDefined {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_Rule_PrinterNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;IpAddress&quot; must be less or equal to 50 characters lenght..
        /// </summary>
        public static string ErrorMessage_Printer_StringLength_IpAddress {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_StringLength_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Manufacturer&quot; must be less or equal to 50 characters lenght..
        /// </summary>
        public static string ErrorMessage_Printer_StringLength_Manufacturer {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_StringLength_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Model&quot; must be less or equal to 50 characters lenght..
        /// </summary>
        public static string ErrorMessage_Printer_StringLength_Model {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_StringLength_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Name&quot; must be less or equal to 50 characters lenght..
        /// </summary>
        public static string ErrorMessage_Printer_StringLength_Name {
            get {
                return ResourceManager.GetString("ErrorMessage_Printer_StringLength_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Action&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Statistic_Required_Action {
            get {
                return ResourceManager.GetString("ErrorMessage_Statistic_Required_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;CampaignType&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Statistic_Required_CampaignType {
            get {
                return ResourceManager.GetString("ErrorMessage_Statistic_Required_CampaignType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;License&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Statistic_Required_License {
            get {
                return ResourceManager.GetString("ErrorMessage_Statistic_Required_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;PrintTrigger&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Statistic_Required_PrintTrigger {
            get {
                return ResourceManager.GetString("ErrorMessage_Statistic_Required_PrintTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;TimeStamp&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Statistic_Required_TimeStamp {
            get {
                return ResourceManager.GetString("ErrorMessage_Statistic_Required_TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Value&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Statistic_Required_Value {
            get {
                return ResourceManager.GetString("ErrorMessage_Statistic_Required_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while syncronizing data..
        /// </summary>
        public static string ErrorMessage_Statistic_Rule_SyncError {
            get {
                return ResourceManager.GetString("ErrorMessage_Statistic_Rule_SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;License&quot; must be 6 characters lenght..
        /// </summary>
        public static string ErrorMessage_Statistic_StringLength_License {
            get {
                return ResourceManager.GetString("ErrorMessage_Statistic_StringLength_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;BarcodeType&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Voucher_Required_BarcodeType {
            get {
                return ResourceManager.GetString("ErrorMessage_Voucher_Required_BarcodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;CampaignId&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Voucher_Required_Campaign_Id {
            get {
                return ResourceManager.GetString("ErrorMessage_Voucher_Required_Campaign_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Code&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Voucher_Required_Code {
            get {
                return ResourceManager.GetString("ErrorMessage_Voucher_Required_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Created&quot; must be informed..
        /// </summary>
        public static string ErrorMessage_Voucher_Required_Created {
            get {
                return ResourceManager.GetString("ErrorMessage_Voucher_Required_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher already used..
        /// </summary>
        public static string ErrorMessage_Voucher_Rule_AlreadyUsed {
            get {
                return ResourceManager.GetString("ErrorMessage_Voucher_Rule_AlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher not found..
        /// </summary>
        public static string ErrorMessage_Voucher_Rule_NotFound {
            get {
                return ResourceManager.GetString("ErrorMessage_Voucher_Rule_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;Code&quot; must be 7 characters lenght..
        /// </summary>
        public static string ErrorMessage_Voucher_StringLength_Code {
            get {
                return ResourceManager.GetString("ErrorMessage_Voucher_StringLength_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Generic_Button_Delete {
            get {
                return ResourceManager.GetString("Generic_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Generic_Button_Edit {
            get {
                return ResourceManager.GetString("Generic_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Generic_ClassName_AppLicense {
            get {
                return ResourceManager.GetString("Generic_ClassName_AppLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Generic_ClassName_Campaign {
            get {
                return ResourceManager.GetString("Generic_ClassName_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Clipart.
        /// </summary>
        public static string Generic_ClassName_GalleryClipart {
            get {
                return ResourceManager.GetString("Generic_ClassName_GalleryClipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Template.
        /// </summary>
        public static string Generic_ClassName_GalleryTemplate {
            get {
                return ResourceManager.GetString("Generic_ClassName_GalleryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Generic_ClassName_Printer {
            get {
                return ResourceManager.GetString("Generic_ClassName_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string Generic_ClassName_Statistic {
            get {
                return ResourceManager.GetString("Generic_ClassName_Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        public static string Generic_ClassName_Voucher {
            get {
                return ResourceManager.GetString("Generic_ClassName_Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting &quot;{0}&quot;..
        /// </summary>
        public static string Generic_ErrorMessage_Delete {
            get {
                return ResourceManager.GetString("Generic_ErrorMessage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while inserting &quot;{0}&quot;..
        /// </summary>
        public static string Generic_ErrorMessage_Insert {
            get {
                return ResourceManager.GetString("Generic_ErrorMessage_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading &quot;{0}&quot;..
        /// </summary>
        public static string Generic_ErrorMessage_Read {
            get {
                return ResourceManager.GetString("Generic_ErrorMessage_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving &quot;{0}&quot;..
        /// </summary>
        public static string Generic_ErrorMessage_Save {
            get {
                return ResourceManager.GetString("Generic_ErrorMessage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating &quot;{0}&quot;..
        /// </summary>
        public static string Generic_ErrorMessage_Update {
            get {
                return ResourceManager.GetString("Generic_ErrorMessage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Generic_Label_Disabled {
            get {
                return ResourceManager.GetString("Generic_Label_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Generic_Label_Enabled {
            get {
                return ResourceManager.GetString("Generic_Label_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Generic_Label_Images {
            get {
                return ResourceManager.GetString("Generic_Label_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string Generic_Label_IpAddress {
            get {
                return ResourceManager.GetString("Generic_Label_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Generic_Label_Name {
            get {
                return ResourceManager.GetString("Generic_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} prints left..
        /// </summary>
        public static string Generic_Label_PrintsLeft {
            get {
                return ResourceManager.GetString("Generic_Label_PrintsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Generic_Label_Type {
            get {
                return ResourceManager.GetString("Generic_Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Generic_Menu_SysTray_Exit {
            get {
                return ResourceManager.GetString("Generic_Menu_SysTray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadget.
        /// </summary>
        public static string Generic_Menu_SysTray_Gadget {
            get {
                return ResourceManager.GetString("Generic_Menu_SysTray_Gadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Generic_Menu_SysTray_Open {
            get {
                return ResourceManager.GetString("Generic_Menu_SysTray_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the action?.
        /// </summary>
        public static string Generic_MessageBox_ConfirmYesOrNo {
            get {
                return ResourceManager.GetString("Generic_MessageBox_ConfirmYesOrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes or No?.
        /// </summary>
        public static string Generic_MessageBox_ConfirmYesOrNoTitle {
            get {
                return ResourceManager.GetString("Generic_MessageBox_ConfirmYesOrNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Generic_MessageBox_ErrorTitle {
            get {
                return ResourceManager.GetString("Generic_MessageBox_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information!.
        /// </summary>
        public static string Generic_MessageBox_InformationTitle {
            get {
                return ResourceManager.GetString("Generic_MessageBox_InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Generic_MessageBox_WarningTitle {
            get {
                return ResourceManager.GetString("Generic_MessageBox_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully..
        /// </summary>
        public static string Generic_SuccessMessage_Delete {
            get {
                return ResourceManager.GetString("Generic_SuccessMessage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved successfully..
        /// </summary>
        public static string Generic_SuccessMessage_Save {
            get {
                return ResourceManager.GetString("Generic_SuccessMessage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active Campaigns found to be printed..
        /// </summary>
        public static string InfoMessage_Campaign_Rule_NoActiveCampaign {
            get {
                return ResourceManager.GetString("InfoMessage_Campaign_Rule_NoActiveCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, your printer works fine!.
        /// </summary>
        public static string InfoMessage_Printer_Info_PrintTestPage {
            get {
                return ResourceManager.GetString("InfoMessage_Printer_Info_PrintTestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any compatible printer was found. Check the list of compatible printers on the right. Please install one and click &quot;Reload&quot; button..
        /// </summary>
        public static string InfoMessage_Printer_Rule_PrinterNotFound {
            get {
                return ResourceManager.GetString("InfoMessage_Printer_Rule_PrinterNotFound", resourceCulture);
            }
        }
    }
}
